runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
consumo_estrato(data, "PROTEINAS", 5)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
consumo_estrato(data, "PROTEINAS", 5)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
consumo_estrato(data, "PROTEINAS", 5)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
consumo_estrato(data, "PROTEINAS", 5)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
consumo_estrato(data, "FRUTOS", 5)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
consumo_estrato(data, "FRUTOS", 5)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/.spyder-py3/temp.py', wdir='C:/Users/isaca/.spyder-py3')
sugerir_valores(grid, (2,0))
runfile('C:/Users/isaca/.spyder-py3/temp.py', wdir='C:/Users/isaca/.spyder-py3')
sugerir_valores(grid, (2,0))
sugerir_valores(grid, (0,1))
runfile('C:/Users/isaca/.spyder-py3/temp.py', wdir='C:/Users/isaca/.spyder-py3')
sugerir_valores(grid, (2,0))
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
consumo_estrato(data, "PROTEINA", 5)
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)
runfile('C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal/esqueletoN4.py', wdir='C:/Users/isaca/OneDrive/Escritorio/Proyectos IP/N4-PROY-i.carvajal')
diagrama_l_m(data)

## ---(Wed Aug 17 11:18:16 2022)---
runfile('C:/Users/isaca/Metodos/circular.py', wdir='C:/Users/isaca/Metodos')
runfile('C:/Users/isaca/Metodos/Numeros_factoriales.py', wdir='C:/Users/isaca/Metodos')
clear
runfile('C:/Users/isaca/Metodos/Numeros_factoriales.py', wdir='C:/Users/isaca/Metodos')
runcell(0, 'C:/Users/isaca/Metodos/Numeros_factoriales.py')
runfile('C:/Users/isaca/Metodos/Numeros_factoriales.py', wdir='C:/Users/isaca/Metodos')
runfile('C:/Users/isaca/Metodos/sucesion_fibonnaci.py', wdir='C:/Users/isaca/Metodos')
runfile('C:/Users/isaca/Metodos/espiral.py', wdir='C:/Users/isaca/Metodos')
clear
runfile('C:/Users/isaca/Metodos/espiral.py', wdir='C:/Users/isaca/Metodos')
runfile('C:/Users/isaca/Metodos/untitled4.py', wdir='C:/Users/isaca/Metodos')
runfile('C:/Users/isaca/Metodos/untitled5.py', wdir='C:/Users/isaca/Metodos')
runfile('C:/Users/isaca/Metodos/Primos.py', wdir='C:/Users/isaca/Metodos')
runcell(0, 'C:/Users/isaca/Metodos/Primos.py')
runfile('C:/Users/isaca/Metodos/Primos.py', wdir='C:/Users/isaca/Metodos')